name: Node CI
on:
  push:
    branches:
      - 'develop'
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: yarn
      - run: npm install -g firebase-tools
      - run: yarn lint
      - run: yarn run build
      - run: firebase deploy --only hosting:development --token=$FIREBASE_TOKEN --project pidz-platform --non-interactive
    env:
      CI: true
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

